### ISSUE TITLE
No GL850G available

### ISSUE THREAD

**Issue by Terumi** [adwuard/dirtywave-m8-headless-keyboard#3]
Hello, since I cannot find a GL850G anywhere, do you know any drop-in replacements for that part?
Thank you~!

**Comment by JoNilsson** [comment]
https://octopart.com/search?q=GL850G

Looks like there are 10s of thousands in stock around the world.

**Comment by adwuard** [comment]
Yeah, It's a widely used solution for a 4 port USB 2.0 Hub.

Here are more places to look for.
- https://www.digipart.com/part/GL850G
- https://www.lcsc.com/product-detail/USB-Converters_Genesys-Logic-GL850G-HHY22_C136617.html

Hope this help.
